services:
  backend:
    build:
      context: ./backend
    container_name: sisinove_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    image: nginx:alpine
    container_name: sisinove_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: always