export const resources = {
  empresas: {
    label: "Gestão de Empresas",
    table: "empresas",
    order: "razao_social ASC",
    id: "id",
    searchable: ["razao_social", "nome_fantasia", "cnpj", "cidade", "responsavel_legal"],
    formFields: [
      { name: "razao_social", label: "Razão Social", type: "text", required: true },
      { name: "nome_fantasia", label: "Nome Fantasia", type: "text" },
      { name: "cnpj", label: "CNPJ", type: "text", required: true },
      { name: "cidade", label: "Cidade", type: "text" },
      { name: "uf", label: "UF", type: "text", defaultValue: "PA" },
      { name: "telefone", label: "Telefone", type: "text" },
      { name: "email", label: "E-mail", type: "email" },
      { name: "responsavel_legal", label: "Responsável Legal", type: "text" },
      { name: "responsavel_acompanhamento", label: "Acompanhamento", type: "text" },
      { name: "data_inicio_parceria", label: "Início Parceria", type: "date" },
      { name: "data_fim_parceria", label: "Fim Parceria", type: "date" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["ativa", "inativa", "suspensa"],
        required: true,
      },
      { name: "observacoes", label: "Observações", type: "textarea" },
      { name: "contrato_pdf", label: "Contrato (URL/File)", type: "file" },
    ],
    chart: { type: "bar", groupBy: "status", title: "Empresas por Status" },
  },

  aprendizes: {
    label: "Cadastro de Aprendizes",
    table: "aprendizes",
    order: "nome ASC",
    id: "id",
    searchable: ["nome", "cpf", "email", "ocupacao", "status"],
    formFields: [
      { name: "empresa_id", label: "Empresa (ID)", type: "number", required: true },
      { name: "nome", label: "Nome Completo", type: "text", required: true },
      { name: "cpf", label: "CPF", type: "text", required: true },
      { name: "rg", label: "RG", type: "text" },
      { name: "data_nascimento", label: "Data Nascimento", type: "date" },
      { name: "telefone", label: "Telefone", type: "text" },
      { name: "email", label: "E-mail", type: "email" },
      { name: "endereco", label: "Endereço", type: "textarea" },
      { name: "responsavel_menor", label: "Responsável (se menor)", type: "text" },
      { name: "ocupacao", label: "Ocupação", type: "text" },
      { name: "cbo", label: "CBO", type: "text" },
      { name: "programa", label: "Programa", type: "text" },
      { name: "carga_horaria_pratica", label: "C.H. Prática", type: "text" },
      { name: "carga_horaria_teorica", label: "C.H. Teórica", type: "text" },
      { name: "dia_aula_teorica", label: "Dia Aula Teórica", type: "text" },
      { name: "horario_aula_teorica", label: "Horário Aula", type: "text" },
      { name: "local_aula_teorica", label: "Local Aula", type: "text", defaultValue: "Laboratório de Informática SISINOVE" },
      { name: "data_inicio_contrato", label: "Início Contrato", type: "date" },
      { name: "data_fim_contrato", label: "Fim Contrato", type: "date" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["ativo", "desligado", "concluido"],
        required: true,
      },
      { name: "contrato_pdf", label: "Contrato PDF", type: "file" },
    ],
    chart: { type: "pie", groupBy: "status", title: "Status dos Aprendizes" },
  },

  frequencias: {
    label: "Frequência Mensal",
    table: "frequencias",
    order: "mes_referencia DESC",
    id: "id",
    searchable: ["mes_referencia", "situacao"],
    formFields: [
      { name: "aprendiz_id", label: "ID Aprendiz", type: "number", required: true },
      { name: "empresa_id", label: "ID Empresa", type: "number", required: true },
      { name: "mes_referencia", label: "Mês Referência (AAAA-MM)", type: "text", required: true },
      { name: "aulas_previstas", label: "Aulas Previstas", type: "number" },
      { name: "presencas", label: "Presenças", type: "number" },
      { name: "faltas", label: "Faltas", type: "number" },
      { name: "faltas_justificadas", label: "Faltas Justificadas", type: "number" },
      { name: "atrasos", label: "Atrasos", type: "number" },
      { name: "percentual_frequencia", label: "% Frequência", type: "number" },
      {
        name: "situacao",
        label: "Situação",
        type: "select",
        options: ["regular", "alerta", "critico"],
      },
      { name: "observacoes", label: "Observações", type: "textarea" },
      { name: "anexo_justificativa", label: "Anexo Justificativa", type: "file" },
    ],
    chart: { type: "bar", groupBy: "situacao", title: "Frequência por Situação" },
  },

  desempenhos: {
    label: "Avaliação de Desempenho",
    table: "desempenhos",
    order: "mes_referencia DESC",
    id: "id",
    searchable: ["mes_referencia", "avaliacao_geral"],
    formFields: [
      { name: "aprendiz_id", label: "ID Aprendiz", type: "number", required: true },
      { name: "empresa_id", label: "ID Empresa", type: "number", required: true },
      { name: "mes_referencia", label: "Mês Referência", type: "text", required: true },
      { name: "participacao", label: "Participação (0-10)", type: "number" },
      { name: "pontualidade", label: "Pontualidade (0-10)", type: "number" },
      { name: "comprometimento", label: "Comprometimento (0-10)", type: "number" },
      { name: "comunicacao", label: "Comunicação (0-10)", type: "number" },
      { name: "relacionamento", label: "Relacionamento (0-10)", type: "number" },
      { name: "atividades", label: "Atividades (0-10)", type: "number" },
      {
        name: "avaliacao_geral",
        label: "Avaliação Geral",
        type: "select",
        options: ["insatisfatorio", "satisfatorio", "bom", "excelente"],
      },
      { name: "observacoes_instrutor", label: "Obs. Instrutor", type: "textarea" },
    ],
    chart: { type: "pie", groupBy: "avaliacao_geral", title: "Nível de Desempenho" },
  },

  auditoria: {
    label: "Auditoria de Alterações",
    table: "auditoria_alteracoes",
    order: "data_hora DESC",
    id: "id",
    searchable: ["usuario", "tabela", "acao"],
    formFields: [
      { name: "usuario", label: "Usuário", type: "text" },
      { name: "tabela", label: "Tabela Alterada", type: "text" },
      { name: "registro_id", label: "ID do Registro", type: "number" },
      { name: "acao", label: "Ação (INSERT/UPDATE/DELETE)", type: "text" },
      { name: "dados_anteriores", label: "Dados Anteriores", type: "textarea" },
      { name: "dados_novos", label: "Dados Novos", type: "textarea" },
      { name: "data_hora", label: "Data/Hora", type: "text" },
    ],
    chart: { type: "bar", groupBy: "acao", title: "Ações do Sistema" },
  },
};

export function getResourceConfig(resource) {
  return resources[resource];
}