export const resources = {
  empresas: {
    label: "Gestão de Empresas",
    table: "empresas",
    order: "razao_social ASC",
    id: "id",
    roles: ['admin'],
    searchable: [
      "razao_social",
      "nome_fantasia",
      "cnpj",
      "cidade",
      "responsavel_legal",
    ],
    formFields: [
      {
        name: "razao_social",
        label: "Razão Social",
        type: "text",
        required: true,
      },
      { name: "cnpj", label: "CNPJ", type: "text", required: true },
      { name: "email", label: "E-mail", type: "email" },
      { name: "responsavel_legal", label: "Responsável Legal", type: "text" },
      { name: "data_inicio_parceria", label: "Início da Parceria", type: "date" },
      { name: "data_fim_parceria", label: "Fim da Parceria", type: "date" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["ativa", "inativa", "suspensa"],
        required: true,
      },
      { name: "attachments", label: "Anexo do Contrato", type: "file" },
    ],
    chart: { type: "bar", groupBy: "status", title: "Empresas por Status" },
  },

  aprendizes: {
    label: "Cadastro de Aprendizes",
    table: "aprendizes",
    order: "nome ASC",
    roles: ['admin', 'empresas'],
    id: "id",
    searchable: ["nome", "cpf", "email", "ocupacao", "status"],
    formFields: [
      {
        name: "empresa_id",
        label: "Empresa",
        type: "select",
        required: true,
        resource: "empresas",
      },
      { name: "nome", label: "Nome Completo", type: "text", required: true },
      { name: "cpf", label: "CPF", type: "text", required: true },
      { name: "data_inicio_contrato", label: "Início do Contrato", type: "date" },
      { name: "data_fim_contrato", label: "Fim do Contrato", type: "date" },
      { name: "status", label: "Situação", type: "select", options: ['ativo', 'inativo'] },
      { name: "ocupacao", label: "Ocupação", type: "text" },
      { name: "cbo", label: "CBO", type: "text" },
      { name: "dia_aula_teorica", label: "Dia Aula Teórica", type: "select", options: ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sabado'] },
      { name: "horario_aula_teorica", label: "Horário Aula", type: "text" },
      { name: "attachments", label: "Contrato PDF", type: "file" },
    ],
    chart: { type: "pie", groupBy: "status", title: "Status dos Aprendizes" },
  },

  frequencias: {
    label: "Frequência Mensal",
    table: "frequencias",
    roles: ['admin', 'empresas'],
    order: "mes_referencia DESC",
    id: "id",
    formFields: [
      {
        name: "aprendiz_id",
        label: "Aprendiz",
        type: "select",
        required: true,
        resource: "aprendizes",
      },
      {
        name: "empresa_id",
        label: "Empresa",
        type: "select",
        required: true,
        resource: "empresas",
      },
      {
        name: "mes_referencia",
        label: "Mês Referência (AAAA-MM)",
        type: "text",
        required: true,
      },
      { name: "aulas_previstas", label: "Aulas Previstas", type: "number" },
      { name: "presencas", label: "Presenças", type: "number" },
      { name: "faltas", label: "Faltas", type: "number" },
      {
        name: "faltas_justificadas",
        label: "Faltas Justificadas",
        type: "number",
      },
      {
        name: "attachments",
        label: "Anexo Justificativa",
        type: "file",
      },
    ],
    chart: {
      type: "bar",
      groupBy: "situacao",
      title: "Frequência por Situação",
    },
  },

  desempenhos: {
    label: "Avaliação de Desempenho",
    table: "desempenhos",
    roles: ['admin', 'empresas'],
    order: "criado_em DESC",
    id: "id",
    searchable: ["aprendiz_id"],
    formFields: [
      {
        name: "aprendiz_id",
        label: "Aprendiz",
        type: "select",
        required: true,
        resource: "aprendizes",
      },
      {
        name: "empresa_id",
        label: "Empresa",
        type: "select",
        required: true,
        resource: "empresas",
      },
      { name: "participacao", label: "Participação (0-10)", type: "number" },
      { name: "pontualidade", label: "Pontualidade (0-10)", type: "number" },
      {
        name: "comprometimento",
        label: "Comprometimento",
        type: "select",
        options: ["satisfatorio", "acompanhamento", "insatisfatorio"],
      },
      {
        name: "observacoes_instrutor",
        label: "Obs. Instrutor",
        type: "textarea",
      },
    ],
    chart: {
      type: "pie",
      groupBy: "comprometimento",
      title: "Nível de Desempenho",
    },
  },

  curriculos: {
    label: "Banco de talentos",
    table: "curriculos",
    roles: ['admin', 'empresas'],
    order: "criado_em DESC",
    id: "id",
    searchable: ["nome", "cpf",],
    formFields: [
      { name: "nome", label: "Nome Completo", type: "text" },
      { name: "cpf", label: "CPF", type: "text" },
      { name: "nascimento", label: "Data de Nascimento", type: "date" },
      { name: "interesse", label: "Área de interesse", type: "text" },
      { name: "endereco", label: "Endereço", type: "text" },
      { name: "cidade", label: "Cidade", type: "select", options: ['Tucuruí', 'Outra'] },
      { name: "estado", label: "Estado", type: "select", options: ['Pará', 'Outro'] },
      { name: "email", label: "E-mail", type: "email" },
      { name: "telefone", label: "Telefone", type: "text" },
      { name: "ctps_assinada", label: "Já trabalhou de carteira assinada?", type: "select", options: ['Sim', 'Não'] },
      { name: "escolaridade", label: "Escolaridade", type: "select", options: ['Fundamental Incompleto', 'Fundamental Completo', 'Ensino Médio Incompleto', 'Ensino Médio Completo', 'Ensino Superior Incompleto', 'Ensino Superior Completo'] },
      { name: "attachments", label: "Anexo do curriculo", type: "file" },
    ],
    chart: { type: "bar", groupBy: "escolaridade", title: "Escolaridade" },
  },
};

export function getResourceConfig(resource) {
  return resources[resource];
}
